# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5e2d052231a3744cd71a6ef97d24e2e2ab8601145d8fc8ee8d492cac153a8544b3bf451c407737d2b92a3ef845271f3e763806a309e67740c8dc33291ce18b

test:
  secret_key_base: 82e8d9971a0606bc4129b179d75d52626bd7ff2731a088d1c468ec685209ed0be5b773862d8a9a9282b5b0d7b17faf7e7d3d7436c1333953219865ccb3958d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
